export const CONSTANTS = {
    REVERSAL: "Auto Reversed",
    MANUAL_REVERSAL: "Manual Reversal",
    SPILLOVER: "Spillover",
    MATCH: "Match",
    PENDING_AUTO_REV: "Pending Auto Reversal",
    CREDIT: "Credit",
    EXCEPTION: "Exception",
    PAIDIN: "PaidIn",
    FINITEM: "FinItem",
    AIRTIME_MPESA: "Mpesa",
    PENDING: "Pending",
    AGENTS: "Agents",
    AUTO_REVERSED: "Auto Reversed",
    RRN_NOT_MATCH: "RRN Mismatch",
    Credit: "C",
    Debit: "D",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    AIRTIME: "301",
    Bundles: "22",
    YES: "Y",
    NO: "N",
    INVESTIGATE: "Investigate",
    DEBIT_CUSTOMER: "Debit Customer",
    MPESA_CHARGE: "Mpesa Charge",
    MOBILE_REV: "Mobile Reversal",
    FLOAT: "Float",
};

export const STATUS_COLORS = {
    REVERSAL: "orange",
    MANUAL_REVERSAL: "orange",
    FLOAT: "cyan",
    MATCH: "green",
    CHARGE: "yellow",
    MPESA_CHARGE: "brown",
    CREDIT: "yellow",
    EXCEPTION: "red",
    PAIDIN: "orange",
    FINITEM: "orange",
    PENDING: "Pending",
    AGENTS: "Agents",
    AUTO_REVERSED: "Auto Reversed",
    RRN_NOT_MATCH: "RRN Mismatch",
    Credit: "C",
    Debit: "D",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    CLOSED: "green",
    RESOLVED: "green",
    DEBIT_CUSTOMER: "red",
    MOBILE_REV: "purple",
    SPILLOVER: "blue",
}
