import { RouteInfo } from "./sidebar.metadata";

export const admin: RouteInfo[] = [
  // ── Main ────────────────────────────────────────────────────────────
  {
    path: "/dashboard/home",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["DASHBOARD_VIEW"],
    submenu: [],
  },

  // ── Assessments group ───────────────────────────────────────────────
  {
    path: "",
    title: "Assessments",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    permissions: [],
    submenu: [],
  },
  {
    path: "/admin/assessments/transactions",
    title: "Transactions",
    moduleName: "transactions",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["TRANSACTION_LIST"],
    submenu: [],
  },
  {
    path: "/admin/assessments/alerts",
    title: "Alerts",
    moduleName: "alerts",
    iconType: "feather",
    icon: "alert-triangle",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["ALERT_LIST"],
    submenu: [],
  },
  {
    path: "/admin/assessments/screening",
    title: "Screening",
    moduleName: "screens",
    iconType: "feather",
    icon: "layers",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["SANCTION_LIST_VIEW"],
    submenu: [],
  },
  {
    path: "/admin/assessments/rules",
    title: "Rules",
    moduleName: "screens",
    iconType: "feather",
    icon: "command",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["SANCTION_LIST_VIEW"],
    submenu: [],
  },
  {
    path: "/admin/assessments/case",
    title: "Case Manager",
    moduleName: "cases",
    iconType: "feather",
    icon: "inbox",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["CASE_LIST"],
    submenu: [],
  },

  // ── Configuration group ───────────────────────────────────────────────
  {
    path: "",
    title: "Configuration",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    permissions: [],
    submenu: [],
  },
  {
    path: "/admin/configurations/branches",
    title: "Branch Management",
    moduleName: "branches",
    iconType: "feather",
    icon: "git-branch",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["BRANCH_LIST"],
    submenu: [],
  },
  {
    path: "/admin/sanctions/entries",
    title: "Entries Management",
    moduleName: "sanctions",
    iconType: "feather",
    icon: "inbox",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["SANCTIONS_LIST_VIEW"],
    submenu: [],
  },
  {
    path: "/admin/sanctions/sources",
    title: "Source Configuration",
    moduleName: "sources",
    iconType: "feather",
    icon: "database",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["SANCTION_SOURCES_VIEW"],
    submenu: [],
  },

  // ── Administration group ─────────────────────────────────────────────
  {
    path: "",
    title: "Administration",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    permissions: [],
    submenu: [],
  },
  {
    path: "/admin/user-management/users",
    title: "Users Management",
    moduleName: "users",
    iconType: "feather",
    icon: "users",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["USER_LIST"],
    submenu: [],
  },
  {
    path: "/admin/role-management/roles",
    title: "Roles & Permissions",
    moduleName: "roles",
    iconType: "feather",
    icon: "shield",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["ROLE_LIST"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/audit-trail",
    title: "Audit Trail",
    moduleName: "audit-trail",
    iconType: "feather",
    icon: "list",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["AUDIT_VIEW"],
    submenu: [],
  },

  // ── Report group ───────────────────────────────────────────────
  {
    path: "",
    title: "Report",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    permissions: [],
    submenu: [],
  },
  {
    path: "/admin/configurations/branches",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "file",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["REPORT_VIEW"],
    submenu: [],
  },
];