import { RouteInfo } from "./sidebar.metadata";

export const admin: RouteInfo[] = [
  // ── Main ────────────────────────────────────────────────────────────
  {
    path: "/dashboard/home",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: [],
    submenu: [],
  },

  // ── Configuration group ───────────────────────────────────────────────
  {
    path: "",
    title: "Configuration",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    permissions: [],
    submenu: [],
  },
  {
    path: "/admin/user-management/branches",
    title: "Branch Management",
    moduleName: "branches",
    iconType: "feather",
    icon: "git-branch",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["BRANCH_LIST"],
    submenu: [],
  },
  {
    path: "/admin/sanctions",
    title: "Entries Management",
    moduleName: "branches",
    iconType: "feather",
    icon: "inbox",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["SANCTIONS_LIST_VIEW"],
    submenu: [],
  },

  // ── Administration group ─────────────────────────────────────────────
  {
    path: "",
    title: "Administration",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    permissions: [],
    submenu: [],
  },
  {
    path: "/admin/user-management/users",
    title: "Users Management",
    moduleName: "users",
    iconType: "feather",
    icon: "users",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["USER_LIST"],
    submenu: [],
  },
  {
    path: "/admin/user-management/roles",
    title: "Roles & Permissions",
    moduleName: "roles",
    iconType: "feather",
    icon: "shield",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["ROLE_LIST"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/audit-trail",
    title: "Audit Trail",
    moduleName: "audit-trail",
    iconType: "feather",
    icon: "list",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    permissions: ["AUDIT_VIEW"],
    submenu: [],
  },

  // ── Compliance group ──────────────────────────────────────────────────
  // {
  //   path: "",
  //   title: "Compliance",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   permissions: [],
  //   submenu: [],
  // },
];
